---
sudo: false
language: ruby
cache: bundler
script: bundle exec rake phantom
rvm: 2.0.0
matrix:
  include:
  - env:
    - JASMINE_VERSION="edge"
  - env:
    - JASMINE_VERSION="2.0"
  - env:
    - JASMINE_VERSION="2.4"
  - env:
    - JASMINE_VERSION="2.5"
  - env:
    - JASMINE_VERSION="2.6"
  - env:
    - JASMINE_VERSION="2.7"
  - env:
    - JASMINE_VERSION="2.8"
