baseurl: //jasmine.github.io
exclude:
  - _tmp
  - src
  - node_modules
  - Rakefile
  - LICENSE
  - README.md
  - Gemfile*
  - "*.json"

collections:
  versions:
    output: true
    permalink: :path
  api:
    output: true
    permalink: api/:path
  faq:
    output: false

sass:
  sass_dir: css/_scss
  style: compressed
